<?php

namespace Tests\Feature;

use App\Models\Member;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ViewMembersTest extends TestCase
{
    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
     */
    private mixed $member;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->member = Member::factory()->create();
    }

    /** @test */
    public function an_admin_can_view_all_members()
    {
        $this->get('/members')
            ->assertSee($this->member->name);
    }

    /** @test */
    public function an_admin_can_view_a_single_member_information()
    {
        $this->get('/members/' .  $this->member->id)
            ->assertSee($this->member->name)
            ->assertSee($this->member->gender);
    }

}
